apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: cms-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-api
  template:
    metadata:
      labels:
        app: cms-api
    spec:
      containers:
        - name: cms-api
          image: REPLACE_ME_ECR_REPO:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
