apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cms-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.do2506.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cms-api-svc
                port:
                  number: 80
